name: Create New Tutorial Request

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'new tutorial')
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Make Changes
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          TEMPLATE_BASE_URL: ${{ vars.TEMPLATE_BASE_URL }}
        run: |
          deno task insert --file ./README.md

      - name: Create commits
        run: |
          git config --global user.name "GetVM Bot"
          git config --global user.email "165758702+getvm-deploy[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Create new tutorial for #${{ github.event.issue.number }}"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: new-tutorial/#${{ github.event.issue.number }}
          delete-branch: true
          title: ${{ github.event.issue.title }}
          body: |
            Update report
            - Auto-generated for #${{ github.event.issue.number }}
          labels: |
            new tutorial
          assignees: huhuhang
