


name: Upload Tutorials

on:
  push:
    branches: ['main']
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      API_SECRET: ${{ secrets.API_SECRET }}
      DUMP_URL: ${{ vars.DUMP_URL }}
      UPLOAD_URL: ${{ vars.UPLOAD_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Upload
        run: |
          deno task upload
