name: Upload Tutorials

on:
  push:
    branches: ['main']
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Upload
        env:
          API_SECRET: ${{ secrets.API_SECRET }}
          UPLOAD_URL: ${{ vars.UPLOAD_URL }}
        run: |
          deno task upload --file ./README.md
